### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by roya0045** [jfbourdon/reperes_geodesiques#1]
https://www.donneesquebec.ca/recherche/fr/dataset/points-geodesiques/resource/774757ff-abbc-4808-8b9a-b2334f7813d2

Est plus simple à acquérir, bien que moins formateur.

**Comment by jfbourdon** [comment]
En fait, c'est suite à un commentaire d'un arpenteur que j'ai justement téléchargé ce shapefile sur Données Québec et que j'ai décidé d'écrire ce script (mais surtout une excuse pour apprendre à faire de l'extraction de données de PDF). Le SHP ne contient que le XY approximatif en NAD83(CSRS) Québec Lambert, le type de repère, son état et le numéro de matricule associé. Bref, c'est largement insuffisant pour des besoins d'arpentage sans les infos contenues dans les fiches.

Mon idée est donc d'effectuer un joint de table entre mon extraction et la table attributaire originale pour regrouper au même endroit plus d'infos pertinentes. Toutefois, n'étant pas moi-même un utilisateur de ces données, je ne sais pas si je prendrai un jour le temps d'améliorer mon script. Avec un peu de chance, le ministère responsable diffusera éventuellement de lui-même les fiches dans un format tabulaire plus facilement interrogeable. J'aurais de la misère à croire que ce ne soit pas déjà disponible à l'interne, mais on peut toujours être surpris avec la fonction publique...
